# Generated by Django 3.2.8 on 2021-11-30 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20211129_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(
                default=datetime.datetime.now, editable=False),
        ),
    ]
